# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67456cda13baf0fd0e86cec8d2aee66fe6b91f82a2dacc72bd8401ed9cb240b7688d0846b8383910eb8efa16deeb728648fb1153be3046e420047e61e45b96c4

test:
  secret_key_base: ac853faaf6be5869af93b640ae61677bdf9bd9931dd3880fa63fa458a682f18fbf495832f7247a0ca87be78855e54260e7101b93fd792ecdc803eab42f45a0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
